### ISSUE TITLE
missing "ui" folder

### ISSUE THREAD

**Issue by paulwong16** [mega002/lm-debugger#3]
Hi Mor,

Thanks for your amazing work. I was trying to build the project and found that there is no UI folder (I guess this should contain some front-end code). Do you have any plan to release the full code in near future?

Thanks!
Paul

**Comment by mega002** [comment]
Paul,

Apologies for this and thanks for opening the issue! :pray:

The `ui` directory was missing by mistake and I just pushed it into [the main branch](../tree/main/ui). 
It includes the front-end react code for the prediction view.

Please let me know if you run into any issues.

Thanks,
Mor
