### ISSUE TITLE
How to adapt this debugger to other Huggingface models, e.g., GPT-J-6B, LLaMA

### ISSUE THREAD

**Issue by jacklanda** [mega002/lm-debugger#6]

**Comment by mega002** [comment]
Hi there,

Thank you for this question!

Different models in HF have different naming schemes (e.g., the first FFN layer is called `c_fc` in GPT-2 and `fc_in` in GPT-J), and different architectures (e.g. the attention and FFN layers in each block are parallel in GPT-J and consecutive in GPT-2, and T5 models have both an encoder and decoder while GPT has only a decoder).

To adapt this code to other models all these differences should be taken into account in two places -- the [flask server](https://github.com/mega002/lm-debugger/tree/main/flask_server) that extracts static and dynamic information from the network's modules, and the [UI](https://github.com/mega002/lm-debugger/tree/main/ui) (how to present that information). 

The more similar the target model's architecture is to the currently implemented architecture, the adaptation will require fewer changes. Specifically, the current implementation supports all GPT-2 models, and adapting it to decoder-only models (like GPT-J and LLaMA) should take only module naming changes (for example, updating the module [this hook](https://github.com/mega002/lm-debugger/blob/main/flask_server/req_res_oop.py#L39) is applied to, that modifies the activation of specific FFN sub-updates). To make such changes, it is often useful to take a look at the HF code implementation of the model (for example, here's the code for [LLaMA](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py)). 

I hope this helps. Please let me know if you have any specific questions or if there is anything I can help with.

Best,
Mor

**Comment by jacklanda** [comment]
> Hi there,
> 
> Thank you for this question!
> 
> Different models in HF have different naming schemes (e.g., the first FFN layer is called `c_fc` in GPT-2 and `fc_in` in GPT-J), and different architectures (e.g. the attention and FFN layers in each block are parallel in GPT-J and consecutive in GPT-2, and T5 models have both an encoder and decoder while GPT has only a decoder).
> 
> To adapt this code to other models all these differences should be taken into account in two places -- the [flask server](https://github.com/mega002/lm-debugger/tree/main/flask_server) that extracts static and dynamic information from the network's modules, and the [UI](https://github.com/mega002/lm-debugger/tree/main/ui) (how to present that information).
> 
> The more similar the target model's architecture is to the currently implemented architecture, the adaptation will require fewer changes. Specifically, the current implementation supports all GPT-2 models, and adapting it to decoder-only models (like GPT-J and LLaMA) should take only module naming changes (for example, updating the module [this hook](https://github.com/mega002/lm-debugger/blob/main/flask_server/req_res_oop.py#L39) is applied to, that modifies the activation of specific FFN sub-updates). To make such changes, it is often useful to take a look at the HF code implementation of the model (for example, here's the code for [LLaMA](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py)).
> 
> I hope this helps. Please let me know if you have any specific questions or if there is anything I can help with.
> 
> Best, Mor

Thank you so much! This issue can be closed now :)
