### ISSUE TITLE
Issue with config file variables 

### ISSUE THREAD

**Issue by Dakingrai** [mega002/lm-debugger#8]
Hi, 

Great work, I enjoyed reading the paper. I wanted to run lm-debugger locally but I'm having issues with some variables of config files. When I try to run the Flask server, I encounter the following error - 

```
Traceback (most recent call last):
  File "flask_server/app.py", line 24, in <module>
    config = pyhocon.ConfigFactory.from_dict(json.loads(_jsonnet.evaluate_file(args.config_path)))
RuntimeError: STATIC ERROR: config_files/gpt2-medium.jsonnet:5:13-22: Unknown variable: SERVER_IP
```
In particular, I'm confused about these variables - server_ip, server_port, elastic_ip, elastic_port, react_ip, react_port, streamlit_ip, and streamlit_port.  I would greatly appreciate it if you could assist me with finding appropriate values to be assigned to these variables. Thank you for your help!

**Comment by mega002** [comment]
Hi @Dakingrai ,

LM-Debugger has two views, the prediction view and the exploration view, each has a backend and frontend.
The prediction view requires running the React application (fronend) + Flask server (backend), and the exploration view requires running the Streamlit server (backend+fronend) and Elasticsearch (backend).

So overall, to have all the UI functionality, one should have 4 services up (`flask`, `react`, `streamlit`, `elastic`) . To have these services communicating with each other in the background, one needs to configure the IP address and port of each service.
If you run the services on the save machine, you could just set all the IP addresses to localhost (127.0.0.1). Regarding the ports -- unless you define special ports, these services will run in their default ports, which you can see in the output messages when running each service. 

I hope this helps. Let me know in case you have more questions.

Mor

**Comment by Dakingrai** [comment]
Got it, thank you for the information!
