### ISSUE TITLE
Methodology to predict tokens layer wise and knockout vectors/scalars.

### ISSUE THREAD

**Issue by abhaskumarsinha** [mega002/lm-debugger#9]
Hello,

That's a good project, I'm just having issues with the online version (https://lm-debugger.apps.allenai.org/) in case that is assistive.

- At each layer (say for GPT medium, layers 0 - 23), how are before and output tokens output? (I suppose, to output *i*-th layer, all the layers after *i* are knocked out with average values on some dataset or zeros??)
- What are dominant sub-updates? (The names like - *L0366*, *L0D248*, etc, do they correspond to some single scalar weights, or attention head vectors, or what?)

Thank You

**Comment by mega002** [comment]
Thanks for these questions.

You can find all the details about the interface in the paper: https://arxiv.org/abs/2204.12130

Specifically for your questions:
(a) The outputs are obtained by taking the hidden representation before/after the i-th MLP layers, projecting it to the output vocabulary, and taking the top-10 tokens with the highest scores.

(b) The dominant sub-updates are the columns in the second MLP metrix with the highest coefficients in the that layer's output for the given input. L0D248 means the vector in the first (0 index) MLP layers at dimension 248.

Best,
Mor
